// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAac4wX94p2N3cRTtvKiNKDh3YmvhEmJ6Y',
    appId: '1:1026668866450:web:9f7a8eeb8007dfa452af4b',
    messagingSenderId: '1026668866450',
    projectId: 'threadchallange-dbseotjs',
    authDomain: 'threadchallange-dbseotjs.firebaseapp.com',
    storageBucket: 'threadchallange-dbseotjs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6aIR-ZzMZhbO_tkcIi0Zl_Ox_Hw3Oi1s',
    appId: '1:1026668866450:android:5469b507a4fda21452af4b',
    messagingSenderId: '1026668866450',
    projectId: 'threadchallange-dbseotjs',
    storageBucket: 'threadchallange-dbseotjs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOGkhZSFmVVvVqJ9zCB7aqcKqvdP0V66Y',
    appId: '1:1026668866450:ios:18fd46d333876feb52af4b',
    messagingSenderId: '1026668866450',
    projectId: 'threadchallange-dbseotjs',
    storageBucket: 'threadchallange-dbseotjs.appspot.com',
    iosBundleId: 'com.example.treadchallange',
  );

}